version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=simple-bank
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "3003:3003"
    environment:
      - ENVIRONMENT=production
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://postgres:1@localhost:5432/simple-bank?sslmode=disable
      - HTTP_SERVER_ADDRESS=0.0.0.0:3002
      - GRPC_SERVER_ADDRESS=0.0.0.0:3003
      - MIGRATION_URL=file://db/migration
      - TOKEN_SYMMETRIC_KEY=12334565434567898765432345675432
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
      - REDIS_ADDRESS=redis:6379
    entrypoint: [ "/app/wait-for.sh","postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]