version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple-bank
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple-bank?sslmode=disable
    entrypoint: [ "/app/wait-for.sh","postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]