// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: account/account_service.proto

package account

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_account_service_proto protoreflect.FileDescriptor

const file_account_account_service_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/account_service.proto\x12\x02pb\x1a account/rpc_create_account.proto\x1a\x15account/account.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xb0\x01\n" +
	"\bAccounts\x12\xa3\x01\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"]\x92A=\x12\x12Create new Account\x1a'Used to create a new account for a user\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/create_accountB-Z+github.com/auronvila/simple-bank/pb/accountb\x06proto3"

var file_account_account_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: pb.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: pb.CreateAccountResponse
}
var file_account_account_service_proto_depIdxs = []int32{
	0, // 0: pb.Accounts.CreateAccount:input_type -> pb.CreateAccountRequest
	1, // 1: pb.Accounts.CreateAccount:output_type -> pb.CreateAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_account_service_proto_init() }
func file_account_account_service_proto_init() {
	if File_account_account_service_proto != nil {
		return
	}
	file_account_rpc_create_account_proto_init()
	file_account_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_service_proto_rawDesc), len(file_account_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_account_service_proto_goTypes,
		DependencyIndexes: file_account_account_service_proto_depIdxs,
	}.Build()
	File_account_account_service_proto = out.File
	file_account_account_service_proto_goTypes = nil
	file_account_account_service_proto_depIdxs = nil
}
