// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: account/account_service.proto

package account

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_account_account_service_proto protoreflect.FileDescriptor

const file_account_account_service_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/account_service.proto\x12\x02pb\x1a account/rpc_create_account.proto\x1a#account/rpc_list_user_account.proto\x1a(account/rpc_update_account_balance.proto\x1a\x15account/account.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe1\x03\n" +
	"\bAccounts\x12\xa3\x01\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"]\x92A=\x12\x12Create new Account\x1a'Used to create a new account for a user\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/create_account\x12\xab\x01\n" +
	"\x10ListUserAccounts\x12\x1b.pb.ListUserAccountsRequest\x1a\x1c.pb.ListUserAccountsResponse\"\\\x92A;\x12\x12List user accounts\x1a%Used to list the accounts of the user\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/list_user_accounts\x12\x80\x01\n" +
	"\x14UpdateAccountBalance\x12\x1f.pb.UpdateAccountBalanceRequest\x1a .pb.UpdateAccountBalanceResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/v1/update_account_balanceB-Z+github.com/auronvila/simple-bank/pb/accountb\x06proto3"

var file_account_account_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),         // 0: pb.CreateAccountRequest
	(*ListUserAccountsRequest)(nil),      // 1: pb.ListUserAccountsRequest
	(*UpdateAccountBalanceRequest)(nil),  // 2: pb.UpdateAccountBalanceRequest
	(*CreateAccountResponse)(nil),        // 3: pb.CreateAccountResponse
	(*ListUserAccountsResponse)(nil),     // 4: pb.ListUserAccountsResponse
	(*UpdateAccountBalanceResponse)(nil), // 5: pb.UpdateAccountBalanceResponse
}
var file_account_account_service_proto_depIdxs = []int32{
	0, // 0: pb.Accounts.CreateAccount:input_type -> pb.CreateAccountRequest
	1, // 1: pb.Accounts.ListUserAccounts:input_type -> pb.ListUserAccountsRequest
	2, // 2: pb.Accounts.UpdateAccountBalance:input_type -> pb.UpdateAccountBalanceRequest
	3, // 3: pb.Accounts.CreateAccount:output_type -> pb.CreateAccountResponse
	4, // 4: pb.Accounts.ListUserAccounts:output_type -> pb.ListUserAccountsResponse
	5, // 5: pb.Accounts.UpdateAccountBalance:output_type -> pb.UpdateAccountBalanceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_account_service_proto_init() }
func file_account_account_service_proto_init() {
	if File_account_account_service_proto != nil {
		return
	}
	file_account_rpc_create_account_proto_init()
	file_account_rpc_list_user_account_proto_init()
	file_account_rpc_update_account_balance_proto_init()
	file_account_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_service_proto_rawDesc), len(file_account_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_account_service_proto_goTypes,
		DependencyIndexes: file_account_account_service_proto_depIdxs,
	}.Build()
	File_account_account_service_proto = out.File
	file_account_account_service_proto_goTypes = nil
	file_account_account_service_proto_depIdxs = nil
}
