// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: account/rpc_get_account_by_id.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_account_rpc_get_account_by_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_rpc_get_account_by_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_account_rpc_get_account_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdResponse) Reset() {
	*x = GetAccountByIdResponse{}
	mi := &file_account_rpc_get_account_by_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdResponse) ProtoMessage() {}

func (x *GetAccountByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_rpc_get_account_by_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByIdResponse) Descriptor() ([]byte, []int) {
	return file_account_rpc_get_account_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByIdResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_account_rpc_get_account_by_id_proto protoreflect.FileDescriptor

const file_account_rpc_get_account_by_id_proto_rawDesc = "" +
	"\n" +
	"#account/rpc_get_account_by_id.proto\x12\x02pb\x1a\x15account/account.proto\"'\n" +
	"\x15GetAccountByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x16GetAccountByIdResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccountB-Z+github.com/auronvila/simple-bank/pb/accountb\x06proto3"

var (
	file_account_rpc_get_account_by_id_proto_rawDescOnce sync.Once
	file_account_rpc_get_account_by_id_proto_rawDescData []byte
)

func file_account_rpc_get_account_by_id_proto_rawDescGZIP() []byte {
	file_account_rpc_get_account_by_id_proto_rawDescOnce.Do(func() {
		file_account_rpc_get_account_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_rpc_get_account_by_id_proto_rawDesc), len(file_account_rpc_get_account_by_id_proto_rawDesc)))
	})
	return file_account_rpc_get_account_by_id_proto_rawDescData
}

var file_account_rpc_get_account_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_rpc_get_account_by_id_proto_goTypes = []any{
	(*GetAccountByIdRequest)(nil),  // 0: pb.GetAccountByIdRequest
	(*GetAccountByIdResponse)(nil), // 1: pb.GetAccountByIdResponse
	(*Account)(nil),                // 2: pb.Account
}
var file_account_rpc_get_account_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetAccountByIdResponse.account:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_rpc_get_account_by_id_proto_init() }
func file_account_rpc_get_account_by_id_proto_init() {
	if File_account_rpc_get_account_by_id_proto != nil {
		return
	}
	file_account_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_rpc_get_account_by_id_proto_rawDesc), len(file_account_rpc_get_account_by_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_rpc_get_account_by_id_proto_goTypes,
		DependencyIndexes: file_account_rpc_get_account_by_id_proto_depIdxs,
		MessageInfos:      file_account_rpc_get_account_by_id_proto_msgTypes,
	}.Build()
	File_account_rpc_get_account_by_id_proto = out.File
	file_account_rpc_get_account_by_id_proto_goTypes = nil
	file_account_rpc_get_account_by_id_proto_depIdxs = nil
}
