// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: account/rpc_list_user_account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountsRequest) Reset() {
	*x = ListUserAccountsRequest{}
	mi := &file_account_rpc_list_user_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountsRequest) ProtoMessage() {}

func (x *ListUserAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_rpc_list_user_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListUserAccountsRequest) Descriptor() ([]byte, []int) {
	return file_account_rpc_list_user_account_proto_rawDescGZIP(), []int{0}
}

type ListUserAccountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated means that an array of account type will be returned
	Accounts      []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAccountsResponse) Reset() {
	*x = ListUserAccountsResponse{}
	mi := &file_account_rpc_list_user_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAccountsResponse) ProtoMessage() {}

func (x *ListUserAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_rpc_list_user_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListUserAccountsResponse) Descriptor() ([]byte, []int) {
	return file_account_rpc_list_user_account_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_account_rpc_list_user_account_proto protoreflect.FileDescriptor

const file_account_rpc_list_user_account_proto_rawDesc = "" +
	"\n" +
	"#account/rpc_list_user_account.proto\x12\x02pb\x1a\x15account/account.proto\"\x19\n" +
	"\x17ListUserAccountsRequest\"C\n" +
	"\x18ListUserAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.pb.AccountR\baccountsB-Z+github.com/auronvila/simple-bank/pb/accountb\x06proto3"

var (
	file_account_rpc_list_user_account_proto_rawDescOnce sync.Once
	file_account_rpc_list_user_account_proto_rawDescData []byte
)

func file_account_rpc_list_user_account_proto_rawDescGZIP() []byte {
	file_account_rpc_list_user_account_proto_rawDescOnce.Do(func() {
		file_account_rpc_list_user_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_rpc_list_user_account_proto_rawDesc), len(file_account_rpc_list_user_account_proto_rawDesc)))
	})
	return file_account_rpc_list_user_account_proto_rawDescData
}

var file_account_rpc_list_user_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_rpc_list_user_account_proto_goTypes = []any{
	(*ListUserAccountsRequest)(nil),  // 0: pb.ListUserAccountsRequest
	(*ListUserAccountsResponse)(nil), // 1: pb.ListUserAccountsResponse
	(*Account)(nil),                  // 2: pb.Account
}
var file_account_rpc_list_user_account_proto_depIdxs = []int32{
	2, // 0: pb.ListUserAccountsResponse.accounts:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_rpc_list_user_account_proto_init() }
func file_account_rpc_list_user_account_proto_init() {
	if File_account_rpc_list_user_account_proto != nil {
		return
	}
	file_account_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_rpc_list_user_account_proto_rawDesc), len(file_account_rpc_list_user_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_rpc_list_user_account_proto_goTypes,
		DependencyIndexes: file_account_rpc_list_user_account_proto_depIdxs,
		MessageInfos:      file_account_rpc_list_user_account_proto_msgTypes,
	}.Build()
	File_account_rpc_list_user_account_proto = out.File
	file_account_rpc_list_user_account_proto_goTypes = nil
	file_account_rpc_list_user_account_proto_depIdxs = nil
}
