// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/users_service_simple_bank.proto

package user

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_users_service_simple_bank_proto protoreflect.FileDescriptor

const file_user_users_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"$user/users_service_simple_bank.proto\x12\x02pb\x1a\x1auser/rpc_create_user.proto\x1a\x19user/rpc_login_user.proto\x1a\x1buser/rpc_verify_email.proto\x1a\x1auser/rpc_update_user.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xba\x04\n" +
	"\x05Users\x12\x86\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"I\x92A,\x12\x0fCreate new user\x1a\x19Used to create a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\x82\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"H\x92A,\x12\n" +
	"Login User\x1a\x1eUsed to login an existing user\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x94\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"W\x92A:\x12\vUpdate User\x1a+Used to partially update a user by username\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\x8b\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"K\x92A0\x12\vVerify User\x1a!Used to verify user email address\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_emailB\x8a\x01\x92A]\x12[\n" +
	"\x0fSimple Bank API\"C\n" +
	"\n" +
	"Auron Vila\x12\x1chttps://github.com/auronvila\x1a\x17auronvila.dev@gmail.com2\x031.4Z(github.com/auronvila/simple-bank/pb/userb\x06proto3"

var file_user_users_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),    // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),   // 2: pb.UpdateUserRequest
	(*VerifyEmailRequest)(nil),  // 3: pb.VerifyEmailRequest
	(*CreateUserResponse)(nil),  // 4: pb.CreateUserResponse
	(*LoginUserResponse)(nil),   // 5: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),  // 6: pb.UpdateUserResponse
	(*VerifyEmailResponse)(nil), // 7: pb.VerifyEmailResponse
}
var file_user_users_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.Users.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.Users.LoginUser:input_type -> pb.LoginUserRequest
	2, // 2: pb.Users.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.Users.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4, // 4: pb.Users.CreateUser:output_type -> pb.CreateUserResponse
	5, // 5: pb.Users.LoginUser:output_type -> pb.LoginUserResponse
	6, // 6: pb.Users.UpdateUser:output_type -> pb.UpdateUserResponse
	7, // 7: pb.Users.VerifyEmail:output_type -> pb.VerifyEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_users_service_simple_bank_proto_init() }
func file_user_users_service_simple_bank_proto_init() {
	if File_user_users_service_simple_bank_proto != nil {
		return
	}
	file_user_rpc_create_user_proto_init()
	file_user_rpc_login_user_proto_init()
	file_user_rpc_verify_email_proto_init()
	file_user_rpc_update_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_users_service_simple_bank_proto_rawDesc), len(file_user_users_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_users_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_user_users_service_simple_bank_proto_depIdxs,
	}.Build()
	File_user_users_service_simple_bank_proto = out.File
	file_user_users_service_simple_bank_proto_goTypes = nil
	file_user_users_service_simple_bank_proto_depIdxs = nil
}
